services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: flask
    depends_on:
      - mongo
    restart: on-failure
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:27017" ]
      interval: 30s
      timeout: 10s
      retries: 5
