CREATE TABLE IF NOT EXISTS ELECTION(
    ELECTION_ID VARCHAR PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR NOT NULL,
    ELECTION_NAME VARCHAR,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    DESCRIPTION VARCHAR,
    ANONYMOUS BOOLEAN NOT NULL DEFAULT FALSE,
    UPDATE_VOTES BOOLEAN NOT NULL DEFAULT TRUE,
    VOTING_STRATEGY VARCHAR NOT NULL DEFAULT 'instant-runoff',
    NUM_WINNERS INTEGER NOT NULL DEFAULT 1,
    CANDIDATES VARCHAR ARRAY NOT NULL,
    VOTES JSONB,
    ROUND_NUMBER INTEGER,
    ROUND_DETAILS VARCHAR ARRAY,
    WINNER VARCHAR
);